# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('authour', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('pitch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitches.Pitch')),
            ],
        ),
    ]
