# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='uuid',
            field=models.CharField(default='', max_length=64),
        ),
    ]
