# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_pitch_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='authour',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 1, 40, 35, 63424, tzinfo=utc), verbose_name='created at'),
        ),
    ]
