# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import pitches.models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_auto_20171119_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='uuid',
            field=models.CharField(default=pitches.models.gen_uuid, max_length=32),
        ),
        migrations.AlterField(
            model_name='vote',
            name='client_id',
            field=models.CharField(max_length=32),
        ),
    ]
