# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0006_auto_20171119_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='text',
            field=models.TextField(),
        ),
    ]
