# Generated by Django 2.0 on 2017-12-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0007_auto_20171119_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('client_id', 'pitch_id')},
        ),
    ]
