# Generated by Django 2.0 on 2017-12-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0012_auto_20171216_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField()),
            ],
        ),
    ]
